// <auto-generated />
using System;
using AppSupportHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppSupportHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppSupportHubDbContext))]
    [Migration("20260902154450_AddChangeAssessments")]
    partial class AddChangeAssessments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppSupportHub.Domain.ChangeAssessments.ChangeAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("acceptance_criteria");

                    b.Property<string>("AssessedByIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assessed_by_identifier");

                    b.Property<string>("BusinessNeed")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("business_need");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk");

                    b.Property<string>("RollbackPlan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rollback_plan");

                    b.Property<string>("SecurityImpact")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("security_impact");

                    b.Property<string>("TechnicalImpact")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("technical_impact");

                    b.Property<string>("TestPlan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("test_plan");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_change_assessments");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_change_assessments_work_item_id");

                    b.ToTable("change_assessments", null, t =>
                        {
                            t.HasCheckConstraint("ck_change_assessments_assessed_by_length", "char_length(assessed_by_identifier) <= 200");

                            t.HasCheckConstraint("ck_change_assessments_narrative_lengths", "char_length(business_need) <= 2000 AND char_length(technical_impact) <= 2000 AND char_length(security_impact) <= 2000 AND char_length(acceptance_criteria) <= 2000 AND char_length(test_plan) <= 2000 AND char_length(rollback_plan) <= 2000");

                            t.HasCheckConstraint("ck_change_assessments_required_text_trimmed", "business_need = btrim(business_need) AND business_need <> '' AND technical_impact = btrim(technical_impact) AND technical_impact <> '' AND security_impact = btrim(security_impact) AND security_impact <> '' AND acceptance_criteria = btrim(acceptance_criteria) AND acceptance_criteria <> '' AND test_plan = btrim(test_plan) AND test_plan <> '' AND rollback_plan = btrim(rollback_plan) AND rollback_plan <> '' AND assessed_by_identifier = btrim(assessed_by_identifier) AND assessed_by_identifier <> ''");

                            t.HasCheckConstraint("ck_change_assessments_risk", "risk IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_change_assessments_timestamp_order", "updated_at_utc >= created_at_utc");
                        });
                });

            modelBuilder.Entity("AppSupportHub.Domain.Systems.ApplicationSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessOwner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("business_owner");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("criticality");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at_utc");

                    b.Property<string>("RetirementReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("retirement_reason");

                    b.Property<string>("SupportTeam")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("support_team");

                    b.Property<string>("TechnicalOwner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("technical_owner");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VendorName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("vendor_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_application_systems");

                    b.HasIndex("Criticality")
                        .HasDatabaseName("ix_application_systems_criticality");

                    b.HasIndex("LifecycleStatus")
                        .HasDatabaseName("ix_application_systems_lifecycle_status");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_application_systems_name");

                    b.HasIndex("SupportTeam")
                        .HasDatabaseName("ix_application_systems_support_team");

                    b.ToTable("application_systems", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_systems_commercial_vendor", "\"type\" <> 'Commercial' OR (vendor_name IS NOT NULL AND vendor_name = btrim(vendor_name) AND vendor_name <> '')");

                            t.HasCheckConstraint("ck_application_systems_criticality", "criticality IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_application_systems_lifecycle_status", "lifecycle_status IN ('Planned', 'Active', 'Maintenance', 'Retired')");

                            t.HasCheckConstraint("ck_application_systems_name_length", "char_length(name::text) <= 150");

                            t.HasCheckConstraint("ck_application_systems_required_text_trimmed", "name::text = btrim(name::text) AND name::text <> '' AND description = btrim(description) AND description <> '' AND business_owner = btrim(business_owner) AND business_owner <> '' AND technical_owner = btrim(technical_owner) AND technical_owner <> '' AND support_team = btrim(support_team) AND support_team <> ''");

                            t.HasCheckConstraint("ck_application_systems_retirement_state", "(lifecycle_status = 'Retired' AND retired_at_utc IS NOT NULL AND retirement_reason IS NOT NULL AND retirement_reason = btrim(retirement_reason) AND retirement_reason <> '') OR (lifecycle_status <> 'Retired' AND retired_at_utc IS NULL AND retirement_reason IS NULL)");

                            t.HasCheckConstraint("ck_application_systems_timestamp_order", "updated_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_application_systems_type", "\"type\" IN ('Commercial', 'Custom')");
                        });
                });

            modelBuilder.Entity("AppSupportHub.Domain.WorkItems.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_system_id");

                    b.Property<string>("AssigneeIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assignee_identifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_summary");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_work_items");

                    b.HasIndex("ApplicationSystemId")
                        .HasDatabaseName("ix_work_items_application_system_id");

                    b.HasIndex("DueAtUtc")
                        .HasDatabaseName("ix_work_items_due_at_utc");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_work_items_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_items_status");

                    b.HasIndex("ApplicationSystemId", "Status")
                        .HasDatabaseName("ix_work_items_application_system_id_status");

                    b.ToTable("work_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_items_due_date", "due_at_utc IS NULL OR due_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_work_items_priority", "priority IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_work_items_required_text_trimmed", "title = btrim(title) AND title <> '' AND description = btrim(description) AND description <> ''");

                            t.HasCheckConstraint("ck_work_items_resolution_state", "(status IN ('Resolved', 'Closed') AND resolution_summary IS NOT NULL AND resolution_summary = btrim(resolution_summary) AND resolution_summary <> '' AND resolved_at_utc IS NOT NULL) OR (status NOT IN ('Resolved', 'Closed') AND resolution_summary IS NULL AND resolved_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_work_items_status", "status IN ('New', 'UnderAnalysis', 'InProgress', 'Blocked', 'Testing', 'Resolved', 'Closed', 'Cancelled')");

                            t.HasCheckConstraint("ck_work_items_timestamp_order", "updated_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_work_items_type", "\"type\" IN ('Incident', 'Enhancement', 'ChangeRequest')");
                        });
                });

            modelBuilder.Entity("AppSupportHub.Domain.WorkItems.WorkItemHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_identifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("event_type");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("previous_value");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_work_item_history_entries");

                    b.HasIndex("WorkItemId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_work_item_history_entries_work_item_id_sequence");

                    b.ToTable("work_item_history_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_item_history_entries_actor_trimmed", "actor_identifier = btrim(actor_identifier) AND actor_identifier <> ''");

                            t.HasCheckConstraint("ck_work_item_history_entries_event_type", "event_type IN ('Created', 'DetailsUpdated', 'Assigned', 'Unassigned', 'PriorityChanged', 'DueDateChanged', 'StatusChanged', 'ResolutionRecorded', 'Reopened', 'Cancelled')");

                            t.HasCheckConstraint("ck_work_item_history_entries_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("AppSupportHub.Domain.ChangeAssessments.ChangeAssessment", b =>
                {
                    b.HasOne("AppSupportHub.Domain.WorkItems.WorkItem", null)
                        .WithOne()
                        .HasForeignKey("AppSupportHub.Domain.ChangeAssessments.ChangeAssessment", "WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_change_assessments_work_items_work_item_id");
                });

            modelBuilder.Entity("AppSupportHub.Domain.WorkItems.WorkItem", b =>
                {
                    b.HasOne("AppSupportHub.Domain.Systems.ApplicationSystem", null)
                        .WithMany()
                        .HasForeignKey("ApplicationSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_items_application_systems_application_system_id");
                });

            modelBuilder.Entity("AppSupportHub.Domain.WorkItems.WorkItemHistoryEntry", b =>
                {
                    b.HasOne("AppSupportHub.Domain.WorkItems.WorkItem", null)
                        .WithMany("History")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_history_entries_work_items_work_item_id");
                });

            modelBuilder.Entity("AppSupportHub.Domain.WorkItems.WorkItem", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
